name: Build MAME

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-2019

    steps:
      - name: Checkout tag mame0235
        uses: actions/checkout@v2
        with:
          ref: mame0235

      - name: Set up MSYS2
        run: |
          choco install msys2
          C:\msys64\usr\bin\bash.exe -lc 'pacman -Syu --noconfirm'

      - name: Install dependencies
        run: |
          C:\msys64\usr\bin\bash.exe -lc 'pacman -S --noconfirm mingw-w64-x86_64-toolchain make git sdl2 cmake python mingw-w64-x86_64-qt5 mingw-w64-x86_64-ccache'

      - name: Clone MAME repository
        run: |
          C:\msys64\usr\bin\bash.exe -lc 'git clone https://github.com/mamedev/mame.git'

      - name: Build MAME with VS2019 UWP
        run: |
          C:\msys64\usr\bin\bash.exe -lc 'cd mame && make vs2019_uwp MSBUILD=1'
