name: UWP Builder

on:
  workflow_dispatch:
    inputs:
      tag_name:
        description: 'Tag Name'
        required: true
        default: 'mame0235'
      package_name:
        description: 'Package Name'
        required: true
        default: 'Xbox_MAME'

jobs:
  build-uwp:
    runs-on: windows-2019

    steps:
      - name: Checkout specific tag
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.tag_name }}

      - name: Setup MSYS2 with MINGW64
        uses: msys2/setup-msys2@v2
        with:
          install: git make mingw-w64-x86_64-gcc mingw-w64-x86_64-python mingw-w64-x86_64-lld mingw-w64-x86_64-libc++
          msystem: MINGW64
          update: true

      - name: Find and set up MSBuild
        shell: pwsh
        id: msbuild
        run: |
          $vsPath = & "${env:ProgramFiles(x86)}\Microsoft Visual Studio\Installer\vswhere.exe" -latest -products * -requires Microsoft.Component.MSBuild -property installationPath
          if ($vsPath) {
            $msbuildPath = Join-Path $vsPath "MSBuild\Current\Bin\MSBuild.exe"
            if (Test-Path $msbuildPath) {
              echo "MSBuild path: $msbuildPath"
              echo "MSBUILD_PATH=$msbuildPath" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8
            } else {
              Write-Error "MSBuild.exe not found!"
              exit 1
            }
          } else {
            Write-Error "Visual Studio with MSBuild not found!"
            exit 1
          }

      - name: Build UWP Project Files
        shell: msys2 {0}
        env:
          MSYSTEM: MINGW64
          ARCHOPTS: "-fuse-ld=lld"
          OVERRIDE_AR: "llvm-ar"
          TOOLS: 1
        run: make vs2019_uwp MSBUILD=1

      - name: Build UWP Solution
        shell: pwsh
        run: |
          & $env:MSBUILD_PATH "${{ env.SolutionPath }}" `
            /p:Platform=${{ env.Platform }} `
            /p:Configuration=${{ env.Configuration }} `
            /p:UapAppxPackageBuildMode=${{ env.BuildMode }} `
            /p:AppxBundle=${{ env.AppxBundle }} `
            /p:PackageCertificateThumbprint="${{ env.THUMBPRINT }}" `
            /p:AppxPackageTestDir="${{ env.PackageOutputRootDir }}\${{ env.PACKAGE_NAME }}" `
            /p:RestorePackagesConfig=true `
            /p:AppxPackageSigningEnabled=true

      - name: Archive build
        shell: pwsh
        run: |
          Compress-Archive -Path "${{ env.PackageOutputRootDir }}\*" -DestinationPath "${{ env.PackageOutputRootDir }}\MAME_Archive.zip"

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: MAME_Archive
          path: ${{ env.PackageOutputRootDir }}/MAME_Archive.zip
